const express = require('express');
const router = express.Router();
const { sequelize } = require('../../models');

// @route   GET /api/reseller/orders
// @desc    Get orders generated by reseller
// @access  Private (Reseller only)
router.get('/', async (req, res) => {
  try {
    const resellerId = req.user.id;
    const { 
      page = 1, 
      limit = 20, 
      status = '', 
      search = '' 
    } = req.query;

    const offset = (parseInt(page) - 1) * parseInt(limit);
    
    let statusCondition = '';
    let searchCondition = '';
    const replacements = { resellerId, limit: parseInt(limit), offset };

    if (status) {
      statusCondition = 'AND o.order_status = :status';
      replacements.status = status;
    }

    if (search) {
      searchCondition = 'AND o.order_number LIKE :search';
      replacements.search = `%${search}%`;
    }

    const orders = await sequelize.query(`
      SELECT 
        o.id,
        o.order_number,
        o.total_amount,
        o.order_status,
        o.payment_status,
        o.created_at,
        o.updated_at,
        c.full_name as customer_name,
        u.mobile as customer_mobile,
        COALESCE(SUM(oi.reseller_commission), 0) as commission_earned,
        GROUP_CONCAT(DISTINCT p.name SEPARATOR ', ') as products
      FROM orders o
      JOIN customers c ON o.customer_id = c.id
      JOIN users u ON c.user_id = u.id
      LEFT JOIN order_items oi ON o.id = oi.order_id
      LEFT JOIN products p ON oi.product_id = p.id
      WHERE o.reseller_id = :resellerId
      ${statusCondition}
      ${searchCondition}
      GROUP BY o.id
      ORDER BY o.created_at DESC
      LIMIT :limit OFFSET :offset
    `, {
      replacements,
      type: sequelize.QueryTypes.SELECT
    });

    // Get total count
    const [countResult] = await sequelize.query(`
      SELECT COUNT(*) as total
      FROM orders o
      WHERE o.reseller_id = :resellerId
      ${statusCondition}
      ${searchCondition}
    `, {
      replacements,
      type: sequelize.QueryTypes.SELECT
    });

    const total = parseInt(countResult.total);
    const totalPages = Math.ceil(total / parseInt(limit));

    res.json({
      status: 'success',
      data: {
        orders: orders.map(o => ({
          ...o,
          total_amount: parseFloat(o.total_amount),
          commission_earned: parseFloat(o.commission_earned)
        })),
        pagination: {
          page: parseInt(page),
          limit: parseInt(limit),
          total,
          totalPages
        }
      }
    });

  } catch (error) {
    console.error('Orders fetch error:', error);
    res.status(500).json({
      status: 'error',
      message: 'Failed to fetch orders',
      error: error.message
    });
  }
});

// @route   GET /api/reseller/orders/:id
// @desc    Get order details
// @access  Private (Reseller only)
router.get('/:id', async (req, res) => {
  try {
    const resellerId = req.user.id;
    const { id } = req.params;

    // Get order details
    const [order] = await sequelize.query(`
      SELECT 
        o.*,
        c.full_name as customer_name,
        u.email as customer_email,
        u.mobile as customer_mobile,
        a.address_line1,
        a.address_line2,
        a.city,
        a.state,
        a.pincode,
        a.country
      FROM orders o
      JOIN customers c ON o.customer_id = c.id
      JOIN users u ON c.user_id = u.id
      LEFT JOIN addresses a ON o.shipping_address_id = a.id
      WHERE o.id = :orderId AND o.reseller_id = :resellerId
    `, {
      replacements: { orderId: id, resellerId },
      type: sequelize.QueryTypes.SELECT
    });

    if (!order) {
      return res.status(404).json({
        status: 'error',
        message: 'Order not found'
      });
    }

    // Get order items
    const items = await sequelize.query(`
      SELECT 
        oi.*,
        p.name as product_name,
        p.reseller_margin,
        (SELECT image_url FROM product_images WHERE product_id = p.id ORDER BY sort_order LIMIT 1) as product_image
      FROM order_items oi
      JOIN products p ON oi.product_id = p.id
      WHERE oi.order_id = :orderId
    `, {
      replacements: { orderId: id },
      type: sequelize.QueryTypes.SELECT
    });

    // Get order status history
    const statusHistory = await sequelize.query(`
      SELECT 
        status,
        notes,
        created_at,
        created_by
      FROM order_status_history
      WHERE order_id = :orderId
      ORDER BY created_at ASC
    `, {
      replacements: { orderId: id },
      type: sequelize.QueryTypes.SELECT
    });

    res.json({
      status: 'success',
      data: {
        order: {
          ...order,
          total_amount: parseFloat(order.total_amount),
          subtotal: parseFloat(order.subtotal),
          discount_amount: parseFloat(order.discount_amount),
          shipping_charges: parseFloat(order.shipping_charges),
          tax_amount: parseFloat(order.tax_amount)
        },
        items: items.map(item => ({
          ...item,
          unit_price: parseFloat(item.unit_price),
          total_price: parseFloat(item.total_price),
          reseller_commission: parseFloat(item.reseller_commission),
          manufacturer_amount: parseFloat(item.manufacturer_amount)
        })),
        statusHistory
      }
    });

  } catch (error) {
    console.error('Order detail error:', error);
    res.status(500).json({
      status: 'error',
      message: 'Failed to fetch order details',
      error: error.message
    });
  }
});

module.exports = router;
